export interface Ending {
  id: string;
  title: string;
  subtitle: string;
  body: string;
  achievedThrough: string;
  image: string;
}

export const endings: Ending[] = [
  {
    id: 'A',
    title: 'NEW BASES OF COOPERATION',
    subtitle: 'Spring 2031 — A New Architecture Emerges',
    body: "Allied coalition creates genuine counterweight. Not through confrontation, but through demonstration of superior model. Network of networks. China powerful but no longer inevitable.\n\nSarah Chen stands at the podium of the Munich Security Conference, February 2031. Not as a panelist — as the architect. The Manila Compact, her brainchild, has transformed from a crisis response into something durable: distributed leadership, transparent burden-sharing, 12-hour decision speed protocols, democratic governance. Eighteen months ago, this was a phone call at 5:30 AM. Now it is the framework.\n\nMaya Patel's allied AI partnerships have become the backbone of a new digital order. Sentinel and its allied counterparts collectively manage $8B in joint and coordinated programs. Shared patents top 12,000. Sentinel AI's valuation: $18B — well above what isolated competition would have produced. Chinese alternatives hold only 8% market share in non-aligned nations. Allied tech cooperation did what no single company could: it made democratic AI the default.\n\nJames Nakamura's allied defense contracts total $4.2B over three years. Stock price up 47%. But the number that matters most to James: employee retention at 94%. People stayed because they believed in what Kōdo Robotics was building.\n\nAnna Karlsson's Nordic Coordination Model has spread to 22 European nations for China-related decisions. What started as four Nordic countries refusing to be bullied individually became a template for collective resilience.\n\nThe Philippines chose Western partnership. Vietnam, Indonesia, Singapore, and South Korea followed. Not because they were told to, but because they were offered something genuine: partnership, not patronage.\n\nChina was forced to recalibrate. Belt & Road restructured with better terms. 'Wolf warrior' diplomacy quietly retired. The Central Committee acknowledged, in internal documents, that 'multipolar coordination' required a different approach. Competition continued — fierce, real, consequential — but within rules that held.\n\nThe world was still dangerous. But the alliances held. And that, in 2031, was everything.",
    achievedThrough:
      'Consistent alliance-building choices, multilateral coordination, shared technological development, and sustained commitment to burden-sharing — not rhetorical promises or dominant leadership.',
    image: '/assets/new_bases_cooperation_ending.webp',
  },
  {
    id: 'B',
    title: 'TRUNDLING ALONG',
    subtitle: 'Spring 2031 — The World Continues Sideways',
    body: "West fails to cohere. Not through collapse, but through persistent failure to choose. Three years of drift become five, then ten. World looks like 2029, just more so.\n\nThe protagonists are at Davos, not Munich. Separate panels, separate meetings, separate agendas. The five people who might have changed everything are in the same building and don't meet.\n\nSarah Chen has been promoted to National Security Advisor — the irony is not lost on her. She has the title she always wanted and the influence she never earned, because the pattern of drift that she warned about became the system she now manages. Draft 23 of her resignation letter sits in an encrypted folder. She has never sent it.\n\nMaya Patel's Sentinel AI is profitable. Revenue: $4.2B. But allied sales are down 60%. The UK, Japan, EU, and Israel have all built independent, incompatible AI ecosystems. 'We own 100% of a fragmenting market,' Maya tells the board. The stock is fine. The strategy is bankrupt.\n\nJames Nakamura's Kōdo Robotics is smaller than it was. Revenue down 35%. The board has fielded an acquisition offer that, in 2029, he would have refused outright. His father built this company for Japan. Three years of drift have left James uncertain what to do with it now.\n\nAnna Karlsson's hybrid 5G approach failed. Chinese malware detected in the civilian network migrated to military systems through 47 connection points. 'We saved 200 million krona,' the politicians said. 'It cost us...' Anna pauses. 'We'll never know what it cost us.'\n\nManila has drifted toward bilateral arrangements with Beijing — a $15B Belt & Road deal closed quietly in late 2030. Malaysia, Thailand, Indonesia, and Vietnam followed in their own ways. NATO spent $185B on allied defense — only 12% coordinated, 61% redundant, 27% incompatible.\n\nNothing collapsed. Nothing was resolved. The future arrived, as futures do, without asking permission. And the pattern held: mobilize, hesitate, accommodate, repeat.",
    achievedThrough:
      'Inconsistent choices, prioritizing short-term comfort, avoiding hard decisions, and fragmented responses. Strategic restraint and flexibility are valuable — but only if eventually converted to action. Persistent deferral of commitment creates a pattern of unreliability.',
    image: '/assets/trundling_along_ending.webp',
  },
  {
    id: 'C',
    title: 'THE CRUCIBLE',
    subtitle: 'Spring 2031 — The World Holds Its Breath',
    body: "High tension, near-miss conflicts, deterrence barely holds. Genuine Cold War 2.0. Trade routes militarized. Trust replaced by verification. Not war, but not peace anyone wanted.\n\nWhite House Situation Room. 3:47 AM. DEFCON 2. A Chinese Type 055 destroyer has illuminated USS Curtis Wilbur with fire control radar. Weapons lock: 14 seconds. It is the ninth incident this month. Sarah Chen, now National Security Advisor, manages what the team calls 'Taiwan Strait Incident 127.' The crisis is standard. The crisis is Wednesday.\n\nMaya Patel's Sentinel AI has been pulled toward defense work as the security environment darkened. The civilian-AI thesis she founded the company on has been crowded out: autonomous targeting, adversarial AI, predictive strike analysis. The latest system runs fully autonomous, zero human latency. Maya tries not to think about what that means.\n\nJames Nakamura's Kōdo Robotics has become a major supplier of allied autonomous defense systems. The commercial business is gone entirely. His son, age 13, asks: 'What will I build?' 'Whatever the world needs.' 'Will the world always need weapons?' 'I hope not.' 'But you're planning like it will.' 'Yes. We are.'\n\nAnna Karlsson watches Sweden's defense budget climb 340% while social programs are cut 18%. Russian aerial incursions: 8 per month in 2029, 47 per month in 2031. Her children have nightmares about sirens.\n\nThe arms race is narrowing the allied advantage. 18 months of tech lead has compressed to 9. China outspends in absolute terms: $380B to $340B. US-China trade is down 57%. Two incompatible technology spheres. US GDP growth: 1.8% versus projected 2.9%.\n\nFour ships. Active weapons locks. Fourteen seconds. 'Law of averages, Mr. President.' Unless something changes fundamentally — economic collapse, regime change, or a strategic choice to de-escalate — this is the world they chose. The safety of a cage, all parties inside, none willing to be the first to leave.",
    achievedThrough:
      'Confrontational choices, military-forward postures, and escalation during the Manila crisis. Strength-based deterrence can prevent catastrophe but creates a permanent high-tension environment that exhausts societies, militarizes economies, and offers no stable resolution.',
    image: '/assets/the_crucible_ending.webp',
  },
  {
    id: 'D',
    title: 'STRATEGIC JUDO',
    subtitle: 'Spring 2031 — Using Strength Against Itself',
    body: "Combined agility of many turns China's strengths into weaknesses. Superior value proposition demonstrated. China forced to compete for influence, not command it. Competition makes everyone better.\n\nSingapore FinTech Festival, April 2031. The Pacific Innovation Coalition is announced: US, Japan, Australia, South Korea, Taiwan, Singapore, Netherlands, UK, Sweden, Canada, India (observer), Vietnam (observer). Combined GDP: $42 trillion. Tech R&D: $340 billion per year.\n\nSarah Chen's asymmetric analysis proved decisive. Chinese centralized manufacturing meant single points of failure. Fast centralized decisions meant mistakes propagated instantly. Belt & Road meant recipient nations resented coercion. Technology theft meant China copied while the alliance innovated — always one step behind.\n\nMaya Patel's allied research network: 23 centers, 8,700 researchers, $18B combined. Distributed 24/7 innovation across time zones. When Chinese Tianhe-4 had a critical vulnerability: 6 weeks offline to patch. When the allied network faced a similar issue: 72 hours, other nodes compensated. Open architecture beats proprietary.\n\nJames Nakamura's allied distributed manufacturing — Australia (materials), US (systems integration), Japan (precision manufacturing) — proved more resilient than any single-nation supply chain. 'We don't match their production speed. We exceed their resilience.'\n\nAnna Karlsson's Nordic Model demonstrated that eight small nations coordinating are more powerful than any one alone. Combined GDP: $2.1 trillion. China chose not to retaliate against four nations simultaneously — it couldn't afford the consequences.\n\nThe Belt & Road countermove worked. Indonesia chose the Pacific Development Framework over BRI. Allied terms: 1.8% interest (vs 2.5%), 25-year terms (vs 20-year), open procurement, full ownership retained, technology transfer included. The talent drain accelerated: 71% of Chinese students in allied universities stayed (vs 62% returning in 2029). Top AI researchers: 78% in allied nations. They chose freedom.\n\nChina adjusted. BRI modified with more grants, less loans, local hiring. 'Wolf warrior' decreased. Multilateral engagement increased. The Central Committee debated whether to continue a strategy that was no longer working.\n\nThe contest continued — but the rules had changed. Democracies didn't match authoritarian strengths. They coordinated around democratic advantages: distributed innovation, governance legitimacy, partnership over coercion. And changing the rules, it turned out, was the whole game.",
    achievedThrough:
      'Creative asymmetric responses, tech-industrial coordination, genuine partnership alternatives, and demonstrating that democratic innovation beats authoritarian replication.',
    image: '/assets/strategic_judo_ending.webp',
  },
];

export const getEnding = (id: string): Ending | undefined =>
  endings.find((e) => e.id === id);
